name: Suggestion
description: Suggest an idea for the macro.
labels: ["suggestion"]

body:
  - type: markdown
    attributes:
      value: |
      
        Thank you for your suggestion! Use the sections below to submit it.

        - All suggestions are welcome!
        - Remember to include sufficient details and context.
        - If you have multiple features to suggest, please submit them in separate issues.
        - Pull requests are accepted. If you know how to code it - go ahead!

  - type: textarea
    id: suggestion
    attributes:
      label: What is your suggestion?
      description: Please provide as much info as possible!
      placeholder: Give a detailed description of your suggested feature. Focus on *what* this feature does, over *why* you want this feature.
    validations:
      required: true

  - type: textarea
    id: improve
    attributes:
      label: How will this improve the macro?
      description: Where would this feature be used and for what purpose?
      placeholder: Explain *why* you want this feature. How will it benefit Skibi Defense Macro users?
    validations:
      required: true

  - type: input
    attributes:
      label: What is your Discord username?
      description: This is not required, but it would help with contacting you and keeping you updated about your suggestion.
